language: csharp
solution: Learning Pad.sln

mono: none
dotnet: 1.1.5

script:
  - dotnet restore web/
  - dotnet build web/
  - dotnet restore TestCases/
  - dotnet build TestCases/
  - dotnet test TestCases/TestCases.csproj
